version: '3.8'

services:
  pinecone:
    image: pinecone/pinecone-local:latest
    container_name: governed-rag-pinecone-local
    ports:
      - "8000:8000"
    environment:
      # These values are for demonstration purposes and are not used by the local image, but can be helpful for consistency
      - PINECONE_API_KEY=my-api-key
      - PINECONE_ENVIRONMENT=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - pinecone_data:/data
    command: ["pinecone", "start", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - default

  # The Redis Caching Layer
  redis-cache:
    image: redis:7-alpine
    container_name: governed-rag-redis-cache
    ports:
      - "6380:6379" # Use a different port to avoid conflicts
    volumes:
      - redis_cache_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

volumes:
  pinecone_data:
    driver: local
  redis_cache_data:
    driver: local

networks:
  default:
    name: governed-rag-network
    driver: bridge


